### ISSUE TITLE
DatabaseInstance replica configuration required for non-mysql instances

### ISSUE THREAD

**Issue by snelsondexcom** [upbound/provider-gcp#379] opened 2023-09-06 21:02 UTC
### What happened?

Per the docs, `replicaConfiguration` should only be applicable to MySQL instances:
> Valid only for MySQL instances

I was able to create a read replica for a PostgreSQL CloudSQL instance using the `DatabaseInstance` resource but it failed to sync with the following error:
```
"error": "cannot run refresh: refresh failed: Missing required argument: \"replica_configuration.0.master_heartbeat_period\" ...
```
Workaround to get the refresh to succeed -- provide an "empty" replica config, e.g.
```
    replicaConfiguration:
    - clientCertificate: ""
      clientKey: ""
      connectRetryInterval: 0
      dumpFilePath: ""
      failoverTarget: false
      masterHeartbeatPeriod: 0
      sslCipher: ""
      username: ""
      verifyServerCertificate: false
```

### How can we reproduce it?

Create a read replica for a PostgreSQL CloudSQL instance.

### What environment did it happen in?

* Crossplane Version: v1.10.2
* Provider Version: v0.35.1
* Kubernetes Version: v1.28.1
* Kubernetes Distribution: GKE

**Comment by turkenf** [comment] 2023-09-06 21:10
Hi @snelsondexcom,

We have a new provider version, could you please try provider-gcp v0.36.0 and let us know?

**Comment by turkenf** [comment] 2023-10-02 12:34
Could not reproduce this issue with the provided information in version 0.37.0, so I am closing for now. 

If you still encounter the same issue, feel free to open a new issue by adding the replication steps and example MRs.

**Closed by turkenf** 2023-10-02 12:34 UTC
Labels: bug, community, needs:triage, needs:information

**Comment by snelsondexcom** [comment] 2023-10-25 21:37
New issue created: https://github.com/upbound/provider-gcp/issues/413
